DROP TABLE PLAYER_STORE;
DROP TABLE STORAGE;
DROP TABLE RECIPE_INGRE;
DROP TABLE PLAYER_RECIPE;
DROP TABLE STORE;
DROP TABLE RECIPE;
DROP TABLE INGRE;
DROP TABLE PLAYER;

DROP SEQUENCE SEQ_INGRE_NO;
DROP SEQUENCE SEQ_RECIPE_NO;

CREATE SEQUENCE SEQ_INGRE_NO
NOCYCLE
NOCACHE;
CREATE SEQUENCE SEQ_RECIPE_NO
NOCYCLE
NOCACHE;


CREATE TABLE PLAYER
(
    PLAYER_NAME    VARCHAR2(30) NOT NULL,
    PLAYER_ID    VARCHAR2(20) NOT NULL,
    PLAYER_PASS    VARCHAR2(20) NOT NULL,
    PLAYER_EMAIL    VARCHAR2(50) NOT NULL,
    PLAYER_GOLD    NUMBER DEFAULT 10000,
    PLAYER_EXP    NUMBER DEFAULT 0
);

COMMENT ON COLUMN PLAYER.PLAYER_NAME IS '닉네임';

COMMENT ON COLUMN PLAYER.PLAYER_ID IS '아이디';

COMMENT ON COLUMN PLAYER.PLAYER_PASS IS '비밀번호';

COMMENT ON COLUMN PLAYER.PLAYER_EMAIL IS '이메일';

COMMENT ON COLUMN PLAYER.PLAYER_GOLD IS '자금';

COMMENT ON COLUMN PLAYER.PLAYER_EXP IS '경험치';

COMMENT ON TABLE PLAYER IS '회원';

CREATE UNIQUE INDEX PLAYER_PK ON PLAYER
( PLAYER_NAME );

ALTER TABLE PLAYER
  ADD CONSTRAINT PLAYER_PK PRIMARY KEY ( PLAYER_NAME )
USING INDEX PLAYER_PK;

INSERT INTO PLAYER VALUES('관리자', 'admin01','admin01','admin01@greedy.com',9999999,9999999);



CREATE TABLE INGRE
(
    INGRE_NO    NUMBER NOT NULL,
    INGRE_NAME    VARCHAR2(20) NOT NULL,
    INGRE_PRICE    NUMBER NOT NULL,
    INGRE_IMG    VARCHAR2(1000)
);

COMMENT ON COLUMN INGRE.INGRE_NO IS '재료번호';

COMMENT ON COLUMN INGRE.INGRE_NAME IS '재료이름';

COMMENT ON COLUMN INGRE.INGRE_PRICE IS '재료가격';

COMMENT ON COLUMN INGRE.INGRE_IMG IS '이미지';

COMMENT ON TABLE INGRE IS '재료';

CREATE UNIQUE INDEX INGRE_PK ON INGRE
( INGRE_NO );

ALTER TABLE INGRE
  ADD CONSTRAINT INGRE_PK PRIMARY KEY ( INGRE_NO )
USING INDEX INGRE_PK;




CREATE TABLE RECIPE
(
    RECIPE_NO    NUMBER NOT NULL,
    FOOD_NAME    VARCHAR2(20) NOT NULL,
    RECIPE_PRICE    NUMBER NOT NULL,
    FOOD_PRICE    NUMBER NOT NULL,
    FOOD_EXP    NUMBER NOT NULL
);

COMMENT ON COLUMN RECIPE.RECIPE_NO IS '레시피번호';

COMMENT ON COLUMN RECIPE.FOOD_NAME IS '요리이름';

COMMENT ON COLUMN RECIPE.RECIPE_PRICE IS '레시피가격';

COMMENT ON COLUMN RECIPE.FOOD_PRICE IS '요리가격';

COMMENT ON COLUMN RECIPE.FOOD_EXP IS '요리경험치';

COMMENT ON TABLE RECIPE IS '레시피';

CREATE UNIQUE INDEX 레시피_PK ON RECIPE
( RECIPE_NO );

ALTER TABLE RECIPE
 ADD CONSTRAINT 레시피_PK PRIMARY KEY ( RECIPE_NO )
 USING INDEX 레시피_PK;
 
 


CREATE TABLE STORE
(
    STORE_LEVEL    NUMBER NOT NULL,
    STORE_NAME    VARCHAR2(20) NOT NULL,
    STORE_PRICE    NUMBER NOT NULL,
    MAX_RECIPE    NUMBER NOT NULL,
    STORE_EXP    NUMBER NOT NULL
);

COMMENT ON COLUMN STORE.STORE_LEVEL IS '가게등급';

COMMENT ON COLUMN STORE.STORE_NAME IS '가게이름';

COMMENT ON COLUMN STORE.STORE_PRICE IS '가게가격';

COMMENT ON COLUMN STORE.MAX_RECIPE IS '최대레시피수';

COMMENT ON COLUMN STORE.STORE_EXP IS '경험치';

COMMENT ON TABLE STORE IS '가게';

CREATE UNIQUE INDEX STORE_PK ON STORE
( STORE_LEVEL );

ALTER TABLE STORE
 ADD CONSTRAINT STORE_PK PRIMARY KEY ( STORE_LEVEL )
 USING INDEX STORE_PK;




CREATE TABLE PLAYER_RECIPE
(
    PLAYER_NAME    VARCHAR2(30) NOT NULL,
    RECIPE_NO    NUMBER NOT NULL
    
);

COMMENT ON COLUMN PLAYER_RECIPE.PLAYER_NAME IS '닉네임';

COMMENT ON COLUMN PLAYER_RECIPE.RECIPE_NO IS '레시피번호';

COMMENT ON TABLE PLAYER_RECIPE IS '보유레시피';

CREATE UNIQUE INDEX 보유레시피_PK ON PLAYER_RECIPE
( RECIPE_NO,PLAYER_NAME );

ALTER TABLE PLAYER_RECIPE
 ADD CONSTRAINT 보유레시피_PK PRIMARY KEY ( RECIPE_NO,PLAYER_NAME )
 USING INDEX 보유레시피_PK; 
 
ALTER TABLE PLAYER_RECIPE 
  ADD FOREIGN KEY (PLAYER_NAME) REFERENCES PLAYER (PLAYER_NAME) ON DELETE CASCADE;
ALTER TABLE PLAYER_RECIPE 
  ADD FOREIGN KEY (RECIPE_NO) REFERENCES RECIPE (RECIPE_NO) ON DELETE CASCADE;
 



CREATE TABLE RECIPE_INGRE
(
    RECIPE_NO    NUMBER NOT NULL,
    INGRE_NO    NUMBER NOT NULL
);

COMMENT ON COLUMN RECIPE_INGRE.RECIPE_NO IS '레시피번호';

COMMENT ON COLUMN RECIPE_INGRE.INGRE_NO IS '재료번호';

COMMENT ON TABLE RECIPE_INGRE IS '레시피재료';

CREATE UNIQUE INDEX 레시피재료_PK ON RECIPE_INGRE
( RECIPE_NO,INGRE_NO );

ALTER TABLE RECIPE_INGRE
 ADD CONSTRAINT 레시피재료_PK PRIMARY KEY ( RECIPE_NO,INGRE_NO )
 USING INDEX 레시피재료_PK; 
 
ALTER TABLE RECIPE_INGRE ADD FOREIGN KEY (INGRE_NO) REFERENCES INGRE (INGRE_NO) ON DELETE CASCADE;
ALTER TABLE RECIPE_INGRE ADD FOREIGN KEY (RECIPE_NO) REFERENCES RECIPE (RECIPE_NO) ON DELETE CASCADE;




CREATE TABLE STORAGE
(
    PLAYER_NAME    VARCHAR2(30) NOT NULL,
    INGRE_NO    NUMBER NOT NULL,
    INGRE_CNT    NUMBER NOT NULL
);

COMMENT ON COLUMN STORAGE.PLAYER_NAME IS '닉네임';

COMMENT ON COLUMN STORAGE.INGRE_NO IS '재료번호';

COMMENT ON COLUMN STORAGE.INGRE_CNT IS '재료개수';

COMMENT ON TABLE STORAGE IS '보유재료';

CREATE UNIQUE INDEX 보유재료_PK ON STORAGE
( PLAYER_NAME,INGRE_NO );

ALTER TABLE STORAGE
 ADD CONSTRAINT 보유재료_PK PRIMARY KEY ( PLAYER_NAME,INGRE_NO )
 USING INDEX 보유재료_PK;
 
ALTER TABLE STORAGE ADD FOREIGN KEY (PLAYER_NAME) REFERENCES PLAYER (PLAYER_NAME) ON DELETE CASCADE;
ALTER TABLE STORAGE ADD FOREIGN KEY (INGRE_NO) REFERENCES INGRE (INGRE_NO) ON DELETE CASCADE;




CREATE TABLE PLAYER_STORE
(
    PLAYER_NAME    VARCHAR2(30) NOT NULL,
    STORE_LEVEL    NUMBER NOT NULL
);

COMMENT ON COLUMN PLAYER_STORE.PLAYER_NAME IS '닉네임';

COMMENT ON COLUMN PLAYER_STORE.STORE_LEVEL IS '가게등급';

COMMENT ON TABLE PLAYER_STORE IS '보유가게';

CREATE UNIQUE INDEX PLAYER_STORE_PK ON PLAYER_STORE
( PLAYER_NAME );

ALTER TABLE PLAYER_STORE
 ADD CONSTRAINT PLAYER_STORE_PK PRIMARY KEY ( PLAYER_NAME )
 USING INDEX PLAYER_STORE_PK;
 
ALTER TABLE PLAYER_STORE ADD FOREIGN KEY (PLAYER_NAME) REFERENCES PLAYER (PLAYER_NAME) ON DELETE CASCADE;
ALTER TABLE PLAYER_STORE ADD FOREIGN KEY (STORE_LEVEL) REFERENCES STORE (STORE_LEVEL) ON DELETE CASCADE;